import pandas as pd

# Revised sample data based on the provided structure
data = {
    "Name": ["John Doe", "Jane Smith", "Carlos Garcia", "Maria Lopez", "Anna Johnson",
             "Michael Brown", "Linda Davis", "James Wilson", "Patricia Martinez", "Robert Taylor",
             "Alice Johnson", "Bob White", "Charlie Black", "Diana Green"],
    "Address": ["San Fernando", "Dagupan", "Bauang", "Agoo", "San Juan", "San Fernando",
                "Rosario", "Caba", "Aringay", "Balaoan", "Luna", "Bacnotan", "Burgos", "Naguilian"],
    "Gender": ["Male", "Female", "Male", "Female", "Female", "Male", "Female", "Male", 
               "Female", "Male", "Female", "Male", "Male", "Female"],
    "Age": [25, 30, 27, 22, 24, 35, 28, 26, 23, 29, 28, 26, 27, 25],
    "Civil Status": ["Single", "Married", "Single", "Single", "Single", "Married", 
                     "Single", "Married", "Single", "Married", "Single", "Married", 
                     "Single", "Single"],
    "Contact Email": ["johndoe@example.com", "janesmith@example.com", "carlosg@example.com", 
                      "marial@example.com", "annaj@example.com", "michaelb@example.com", 
                      "lindad@example.com", "jamesw@example.com", "patriciam@example.com", 
                      "robertt@example.com", "alicej@example.com", "bobw@example.com", 
                      "charlieb@example.com", "dianag@example.com"],
    "Contact Number": ["09123456789", "09987654321", "09111111111", "09222222222", 
                       "09333333333", "09444444444", "09555555555", "09666666666", 
                       "09777777777", "09888888888", "09999999999", "09090909090", 
                       "09191919191", "09292929292"],
    "Prior Education": ["High School", "College", "ALS", "High School", "Undergraduate", 
                        "Displaced Worker", "OFW Returnee", "High School", "College", "ALS", 
                        "High School", "College", "ALS", "High School"],
    "Course Completed": ["Computer Systems Servicing", "Computer Systems Servicing", 
                         "Computer Systems Servicing", "Web Development", "Web Development", 
                         "Web Development", "Animal Production Swine", "Animal Production Swine", 
                         "Animal Production Swine", "Bread and Pastry Production", 
                         "Bread and Pastry Production", "Bread and Pastry Production", 
                         "Bread and Pastry Production", "Bread and Pastry Production"],
    "Specialization": ["Networking", "Hardware", "Software", "Frontend Development",
                       "Backend Development", "Full Stack", "Swine Production",
                       "Poultry Production", "Swine Production", "Baking", 
                       "Decorating", "Baking", "Decorating", "Baking"],
    "Date Started": ["01/01/2021", "01/01/2021", "01/01/2021", "01/01/2021", "01/01/2021", 
                     "01/01/2021", "01/01/2021", "01/01/2021", "01/01/2021", "01/01/2021", 
                     "01/01/2021", "01/01/2021", "01/01/2021", "01/01/2021"],
    "Date Graduated": ["12/31/2021", "12/31/2021", "12/31/2021", "12/31/2021", "12/31/2021", 
                       "12/31/2021", "12/31/2021", "12/31/2021", "12/31/2021", "12/31/2021", 
                       "12/31/2021", "12/31/2021", "12/31/2021", "12/31/2021"],
    "Honors": ["None", "None", "None", "None", "None", "None", "None", "None", 
               "None", "Honors", "Honors", "Honors", "None", "None"],
    "OJT Details": ["Company A", "Company B", "Company C", "Company D", "Company E", 
                    "Company F", "Farm I", "Farm J", "Farm K", "Bakery M", 
                    "Bakery N", "Bakery O", "Bakery P", "Bakery Q"],
    "Technical Skills": ["Hardware, Software", "Networking", "Software", "HTML, CSS, JavaScript", 
                         "Python, Django", "HTML, CSS, JavaScript", "Animal Husbandry", 
                         "Poultry Production", "Swine Production", "Baking, Decorating", 
                         "Baking", "Decorating", "Baking, Decorating", "Baking"],
    "Soft Skills": ["Communication, Teamwork", "Problem Solving", "Teamwork", "Creativity, Problem Solving", 
                    "Analytical Skills", "Creativity, Problem Solving", "Problem Solving", 
                    "Teamwork", "Problem Solving, Teamwork", "Creativity, Time Management", 
                    "Creativity", "Time Management", "Creativity, Time Management", 
                    "Creativity"],
    "Leadership Roles": ["Team Leader", "Team Leader", "Team Leader", "Project Leader", 
                         "Project Leader", "Project Leader", "Team Member", "Team Member", 
                         "Team Member", "Supervisor", "Supervisor", "Supervisor", 
                         "Supervisor", "Supervisor"],
    "Name of Organization": ["TechCorp", "NetTech", "SoftWorks", "WebGurus", "CodeMasters", 
                             "Techies", "AgriPros", "Farmers Inc.", "AgriPros", "BakeryWorld", 
                             "BakersHub", "SweetTreats", "BakeIt", "BreadBakery"],
    "Type of Organization": ["Private", "Private", "Private", "Private", "Private", 
                             "Private", "Private", "Private", "Private", "Private", 
                             "Private", "Private", "Private", "Private"],
    "Employment Type": ["Full-time", "Full-time", "Full-time", "Part-time", "Full-time", 
                        "Part-time", "Self-employed", "Unemployed", "Self-employed", 
                        "Part-time", "Full-time", "Part-time", "Self-employed", "Unemployed"],
    "Employment Start Date": ["01/15/2022", "02/01/2022", "03/01/2022", "04/01/2022", "05/01/2022", 
                              "01/20/2022", "02/15/2022", "", "03/10/2022", "04/05/2022", 
                              "05/20/2022", "01/25/2022", "02/20/2022", ""],
    "Industry Type": ["IT", "IT", "IT", "IT", "IT", "IT", "Agriculture", "None", "Agriculture", 
                      "Food Service", "Food Service", "Food Service", "Food Service", "Food Service"],
    "Job Title": ["Network Engineer", "IT Support", "Software Developer", "Frontend Developer", 
                  "Backend Developer", "Full Stack Developer", "Farmer", "None", "Swine Farmer", 
                  "Baker", "Pastry Chef", "Decorator", "Baker", "None"],
    "Years in Company": [1, 2, 1, 2, 1, 1, 2, 0, 2, 1, 2, 1, 2, 0],
    "Employment Status": ["Employed", "Employed", "Employed", "Employed", "Employed", 
                          "Employed", "Self-employed", "Unemployed", "Self-employed", 
                          "Employed", "Employed", "Employed", "Self-employed", "Unemployed"],
    "Monthly Income Range": ["20,000 - 30,000", "20,000 - 30,000", "20,000 - 30,000", "15,000 - 20,000", 
                             "25,000 - 35,000", "15,000 - 20,000", "10,000 - 15,000", "0", "10,000 - 15,000", 
                             "15,000 - 20,000", "15,000 - 20,000", "15,000 - 20,000", "10,000 - 15,000", "0"],
    "Place of Work": ["San Fernando", "San Fernando", "San Fernando", "Dagupan", "San Juan", 
                      "San Fernando", "Rosario", "None", "Caba", "Aringay", 
                      "Balaoan", "Luna", "Bacnotan", "None"],
    "Career Progression": ["Promoted", "Promoted", "Promoted", "Promoted", "Promoted", 
                           "Promoted", "None", "None", "None", "Promoted", 
                           "Promoted", "Promoted", "None", "None"],
    "Job Satisfaction": [4, 4, 4, 3, 5, 3, 5, 0, 5, 4, 5, 4, 5, 0],
    "Enrollment Date": ["01/01/2023", "01/01/2023", "01/01/2023", "01/01/2023", "01/01/2023", 
                        "01/01/2023", "01/01/2023", "01/01/2023", "01/01/2023", "01/01/2023", 
                        "01/01/2023", "01/01/2023", "01/01/2023", "01/01/2023"],
    "Degree Program": ["BS Computer Science", "BS Information Technology", "BS Software Engineering", 
                       "BS Computer Science", "BS Computer Science", "BS Information Technology", 
                       "BS Agriculture", "None", "BS Agriculture", "BS Culinary Arts", 
                       "BS Culinary Arts", "BS Culinary Arts", "BS Culinary Arts", "None"],
    "University/Institution": ["XYZ University", "UVW Institute", "LMN College", "XYZ University", 
                               "RST University", "UVW Institute", "LMN College", "None", 
                               "LMN College", "ABC Institute", "ABC Institute", "ABC Institute", 
                               "ABC Institute", "None"],
    "University Address": ["San Fernando", "San Fernando", "San Fernando", "Dagupan", 
                           "San Juan", "San Fernando", "Rosario", "None", "Caba", "Aringay", 
                           "Balaoan", "Luna", "Bacnotan", "None"],
    "Reasons for Further Studies": ["Career Advancement", "Skill Enhancement", "Skill Enhancement", 
                                    "Career Advancement", "Career Advancement", "Skill Enhancement", 
                                    "Interest in Agriculture", "None", "Interest in Agriculture", 
                                    "Passion for Baking", "Passion for Baking", "Passion for Baking", 
                                    "Passion for Baking", "None"]
}

# Create DataFrame
df = pd.DataFrame(data)

# Save to Excel using raw string or forward slashes to avoid unicode error
file_path = r'C:\Users\Chester\Documents\generate.xlsx'
df.to_excel(file_path, index=False)

print(f"Sample data has been saved to {file_path}")
